# 生效前执行：pre-commit install
exclude: '\.pb\.go$'
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
#      - id: golangci-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=20]
      - id: validate-toml
      - id: go-mod-tidy
      - id: go-unit-tests
        pass_filenames: false
      # - id: go-build
